### PR TITLE
Implemented scripts for seeding keycloak.

### PR DESCRIPTION
**Pull request by inbarbarkai**

### CODE REVIEW

**Comment by yarons** [comment]
I like it, it's really necessary but I'm wondering if there's an integral way to implement it, I think I found a way to do it automatically directly from docker-compose like that:

``` yaml
keycloak:
  image: bitnami/keycloak:latest
  volumes:
    - /path/to/init-scripts:/docker-entrypoint-initdb.d
````

Can I try before merging?

**Comment by inbarbarkai** [comment]
Sure

**Comment by inbarbarkai** [comment]
@yarons  Since your suggestion cannot work at this point, don't you think it is better to merge?

**Comment by yarons** [comment]
Yeah, I'll merge and continue to play with it later.

So far we have this:
https://github.com/bitnami/bitnami-docker-keycloak/issues/41

**Review by yarons — APPROVED** [review]

**Comment by yarons** [comment]
Just don't remove the branch yet, I'm still working on it :)

**Pull request merged**
