### PR TITLE
Keycloak seed fix

### PR DESCRIPTION
**Pull request by yarons**
Added service accounts enabled.

### CODE REVIEW

**Review by KamiTzayig — APPROVED** [review]
hope it works

**Comment by inbarbarkai** [comment]
Why did you enable service accounts?

**Comment by yarons** [comment]
It doesn't work without it, I tried.

**Comment by inbarbarkai** [comment]
Then you did it wrong

**Comment by yarons** [comment]
OK, what are the options?
When you try puting invitease as client id and the uuid as client secret it doesn't work in /docs, there's an error prompt saying thay you didn't enable service account.
It's either that or I entered the details in the wrong place out of the several for auth in /docs.

**Comment by inbarbarkai** [comment]
Are you using authorization code flow?

**Comment by yarons** [comment]
I'm using the Authorize button at the top, there are numerous option for authorization with different fields, when trying this specific client_id/client_secret option I'm getting an error message which is solved when applying this setting to the client_id.

**Comment by inbarbarkai** [comment]
OK, you should use the password flow there, that will authenticate you as a user.
I'm working on a way to verify the user role.
If you'll use the credentials flow, you will be denied by lack of permissions.

**Comment by yarons** [comment]
So I need to add another user for this purpose to be able to connect with that client credentials?
It's only for testing purposes I guess.

**Comment by inbarbarkai** [comment]
You can use the admin credentials with the invitease client credentials.

**Comment by yarons** [comment]
I removed "Service Accounts Enabled", switched to the user/password flow, I got another error that was resolved by switching "Direct Access Grants Enabled" on, should I enable this in the seed instead?

**Comment by inbarbarkai** [comment]
You can seed that

**Comment by yarons** [comment]
Cool, wasn't sure it's the correct practice, thanks.

**Comment by inbarbarkai** [comment]
It is not, for ease of test it will suffice.

**Pull request merged**
